//HOMEPAGE || videos
export const videoList = [
    {thumbnail: '../media/imgs/zombie.webp',
    channel: '../media/imgs/youngk.png',
    title: 'DAY6 "ZOMBIE (English Ver.)" Lyric Video',
    channelName: "DAY6",
    views: "9.5M",
    age: "1 year"},
    
    {thumbnail: '../media/imgs/zombie.webp',
    channel: '../media/imgs/youngk.png',
    title: 'DAY6 "ZOMBIE (English Ver.)" Lyric Video',
    channelName: "DAY6",
    views: "9.5M",
    age: "1 year"},
    
    {thumbnail: '../media/imgs/zombie.webp',
    channel: '../media/imgs/youngk.png',
    title: 'DAY6 "ZOMBIE (English Ver.)" Lyric Video',
    channelName: "DAY6",
    views: "9.5M",
    age: "1 year"},
    
    {thumbnail: '../media/imgs/zombie.webp',
    channel: '../media/imgs/youngk.png',
    title: 'DAY6 "ZOMBIE (English Ver.)" Lyric Video',
    channelName: "DAY6",
    views: "9.5M",
    age: "1 year"},
    
    {thumbnail: '../media/imgs/zombie.webp',
    channel: '../media/imgs/youngk.png',
    title: 'DAY6 "ZOMBIE (English Ver.)" Lyric Video',
    channelName: "DAY6",
    views: "9.5M",
    age: "1 year"},
    
    {thumbnail: '../media/imgs/zombie.webp',
    channel: '../media/imgs/youngk.png',
    title: 'DAY6 "ZOMBIE (English Ver.)" Lyric Video',
    channelName: "DAY6",
    views: "9.5M",
    age: "1 year"},
    
    {thumbnail: '../media/imgs/zombie.webp',
    channel: '../media/imgs/youngk.png',
    title: 'DAY6 "ZOMBIE (English Ver.)" Lyric Video',
    channelName: "DAY6",
    views: "9.5M",
    age: "1 year"},
    
    {thumbnail: '../media/imgs/zombie.webp',
    channel: '../media/imgs/youngk.png',
    title: 'DAY6 "ZOMBIE (English Ver.)" Lyric Video',
    channelName: "DAY6",
    views: "9.5M",
    age: "1 year"},
    
    {thumbnail: '../media/imgs/zombie.webp',
    channel: '../media/imgs/youngk.png',
    title: 'DAY6 "ZOMBIE (English Ver.)" Lyric Video',
    channelName: "DAY6",
    views: "9.5M",
    age: "1 year"},
    
    {thumbnail: '../media/imgs/zombie.webp',
    channel: '../media/imgs/youngk.png',
    title: 'DAY6 "ZOMBIE (English Ver.)" Lyric Video',
    channelName: "DAY6",
    views: "9.5M",
    age: "1 year"},
    
    {thumbnail: '../media/imgs/zombie.webp',
    channel: '../media/imgs/youngk.png',
    title: 'DAY6 "ZOMBIE (English Ver.)" Lyric Video',
    channelName: "DAY6",
    views: "9.5M",
    age: "1 year"},
    
    {thumbnail: '../media/imgs/zombie.webp',
    channel: '../media/imgs/youngk.png',
    title: 'DAY6 "ZOMBIE (English Ver.)" Lyric Video',
    channelName: "DAY6",
    views: "9.5M",
    age: "1 year"},
    
    {thumbnail: '../media/imgs/zombie.webp',
    channel: '../media/imgs/youngk.png',
    title: 'DAY6 "ZOMBIE (English Ver.)" Lyric Video',
    channelName: "DAY6",
    views: "9.5M",
    age: "1 year"},
    
    {thumbnail: '../media/imgs/zombie.webp',
    channel: '../media/imgs/youngk.png',
    title: 'DAY6 "ZOMBIE (English Ver.)" Lyric Video',
    channelName: "DAY6",
    views: "9.5M",
    age: "1 year"},
    
    {thumbnail: '../media/imgs/zombie.webp',
    channel: '../media/imgs/youngk.png',
    title: 'DAY6 "ZOMBIE (English Ver.)" Lyric Video',
    channelName: "DAY6",
    views: "9.5M",
    age: "1 year"},
    
    {thumbnail: '../media/imgs/zombie.webp',
    channel: '../media/imgs/youngk.png',
    title: 'DAY6 "ZOMBIE (English Ver.)" Lyric Video',
    channelName: "DAY6",
    views: "9.5M",
    age: "1 year"},
    
    {thumbnail: '../media/imgs/zombie.webp',
    channel: '../media/imgs/youngk.png',
    title: 'DAY6 "ZOMBIE (English Ver.)" Lyric Video',
    channelName: "DAY6",
    views: "9.5M",
    age: "1 year"},
    
    {thumbnail: '../media/imgs/zombie.webp',
    channel: '../media/imgs/youngk.png',
    title: 'DAY6 "ZOMBIE (English Ver.)" Lyric Video',
    channelName: "DAY6",
    views: "9.5M",
    age: "1 year"},
    
    {thumbnail: '../media/imgs/zombie.webp',
    channel: '../media/imgs/youngk.png',
    title: 'DAY6 "ZOMBIE (English Ver.)" Lyric Video',
    channelName: "DAY6",
    views: "9.5M",
    age: "1 year"},
    
    {thumbnail: '../media/imgs/zombie.webp',
    channel: '../media/imgs/youngk.png',
    title: 'DAY6 "ZOMBIE (English Ver.)" Lyric Video',
    channelName: "DAY6",
    views: "9.5M",
    age: "1 year"},
    
    {thumbnail: '../media/imgs/zombie.webp',
    channel: '../media/imgs/youngk.png',
    title: 'DAY6 "ZOMBIE (English Ver.)" Lyric Video',
    channelName: "DAY6",
    views: "9.5M",
    age: "1 year"},
    
    {thumbnail: '../media/imgs/zombie.webp',
    channel: '../media/imgs/youngk.png',
    title: 'DAY6 "ZOMBIE (English Ver.)" Lyric Video',
    channelName: "DAY6",
    views: "9.5M",
    age: "1 year"},
    
    {thumbnail: '../media/imgs/zombie.webp',
    channel: '../media/imgs/youngk.png',
    title: 'DAY6 "ZOMBIE (English Ver.)" Lyric Video',
    channelName: "DAY6",
    views: "9.5M",
    age: "1 year"},
    
    {thumbnail: '../media/imgs/zombie.webp',
    channel: '../media/imgs/youngk.png',
    title: 'DAY6 "ZOMBIE (English Ver.)" Lyric Video',
    channelName: "DAY6",
    views: "9.5M",
    age: "1 year"},
    
    {thumbnail: '../media/imgs/zombie.webp',
    channel: '../media/imgs/youngk.png',
    title: 'DAY6 "ZOMBIE (English Ver.)" Lyric Video',
    channelName: "DAY6",
    views: "9.5M",
    age: "1 year"},
    
    {thumbnail: '../media/imgs/zombie.webp',
    channel: '../media/imgs/youngk.png',
    title: 'DAY6 "ZOMBIE (English Ver.)" Lyric Video',
    channelName: "DAY6",
    views: "9.5M",
    age: "1 year"},
    
    {thumbnail: '../media/imgs/zombie.webp',
    channel: '../media/imgs/youngk.png',
    title: 'DAY6 "ZOMBIE (English Ver.)" Lyric Video',
    channelName: "DAY6",
    views: "9.5M",
    age: "1 year"}
]