//HOMEPAGE || videos
export const videoList = [
    {thumbnail: 'imgs/tempo_thumbnail.jpg',
    channel: '../media/imgs/channel.PNG',
    title: "Made In The AM - Full",
    channelName: "Top Music Vevo",
    views: "13k",
    age: "1 week"},
    
    {thumbnail: 'imgs/tempo_thumbnail.jpg',
    channel: '../media/imgs/channel.PNG',
    title: "Made In The AM - Full",
    channelName: "Top Music Vevo",
    views: "13k",
    age: "1 week"},
    
    {thumbnail: 'imgs/tempo_thumbnail.jpg',
    channel: '../media/imgs/channel.PNG',
    title: "Made In The AM - Full",
    channelName: "Top Music Vevo",
    views: "13k",
    age: "1 week"},
    
    {thumbnail: 'imgs/tempo_thumbnail.jpg',
    channel: '../media/imgs/channel.PNG',
    title: "Made In The AM - Full",
    channelName: "Top Music Vevo",
    views: "13k",
    age: "1 week"},
    
    {thumbnail: 'imgs/tempo_thumbnail.jpg',
    channel: '../media/imgs/channel.PNG',
    title: "Made In The AM - Full",
    channelName: "Top Music Vevo",
    views: "13k",
    age: "1 week"},
    
    {thumbnail: 'imgs/tempo_thumbnail.jpg',
    channel: '../media/imgs/channel.PNG',
    title: "Made In The AM - Full",
    channelName: "Top Music Vevo",
    views: "13k",
    age: "1 week"},
    
    {thumbnail: 'imgs/tempo_thumbnail.jpg',
    channel: '../media/imgs/channel.PNG',
    title: "Made In The AM - Full",
    channelName: "Top Music Vevo",
    views: "13k",
    age: "1 week"},
    
    {thumbnail: 'imgs/tempo_thumbnail.jpg',
    channel: '../media/imgs/channel.PNG',
    title: "Made In The AM - Full",
    channelName: "Top Music Vevo",
    views: "13k",
    age: "1 week"},
    
    {thumbnail: 'imgs/tempo_thumbnail.jpg',
    channel: '../media/imgs/channel.PNG',
    title: "Made In The AM - Full",
    channelName: "Top Music Vevo",
    views: "13k",
    age: "1 week"},
    
    {thumbnail: 'imgs/tempo_thumbnail.jpg',
    channel: '../media/imgs/channel.PNG',
    title: "Made In The AM - Full",
    channelName: "Top Music Vevo",
    views: "13k",
    age: "1 week"},
    
    {thumbnail: 'imgs/tempo_thumbnail.jpg',
    channel: '../media/imgs/channel.PNG',
    title: "Made In The AM - Full",
    channelName: "Top Music Vevo",
    views: "13k",
    age: "1 week"},
    
    {thumbnail: 'imgs/tempo_thumbnail.jpg',
    channel: '../media/imgs/channel.PNG',
    title: "Made In The AM - Full",
    channelName: "Top Music Vevo",
    views: "13k",
    age: "1 week"},
    
    {thumbnail: 'imgs/tempo_thumbnail.jpg',
    channel: '../media/imgs/channel.PNG',
    title: "Made In The AM - Full",
    channelName: "Top Music Vevo",
    views: "13k",
    age: "1 week"},
    
    {thumbnail: 'imgs/tempo_thumbnail.jpg',
    channel: '../media/imgs/channel.PNG',
    title: "Made In The AM - Full",
    channelName: "Top Music Vevo",
    views: "13k",
    age: "1 week"},
    
    {thumbnail: 'imgs/tempo_thumbnail.jpg',
    channel: '../media/imgs/channel.PNG',
    title: "Made In The AM - Full",
    channelName: "Top Music Vevo",
    views: "13k",
    age: "1 week"},
    
    {thumbnail: 'imgs/tempo_thumbnail.jpg',
    channel: '../media/imgs/channel.PNG',
    title: "Made In The AM - Full",
    channelName: "Top Music Vevo",
    views: "13k",
    age: "1 week"},
    
    {thumbnail: 'imgs/tempo_thumbnail.jpg',
    channel: '../media/imgs/channel.PNG',
    title: "Made In The AM - Full",
    channelName: "Top Music Vevo",
    views: "13k",
    age: "1 week"},
    
    {thumbnail: 'imgs/tempo_thumbnail.jpg',
    channel: '../media/imgs/channel.PNG',
    title: "Made In The AM - Full",
    channelName: "Top Music Vevo",
    views: "13k",
    age: "1 week"},
    
    {thumbnail: 'imgs/tempo_thumbnail.jpg',
    channel: '../media/imgs/channel.PNG',
    title: "Made In The AM - Full",
    channelName: "Top Music Vevo",
    views: "13k",
    age: "1 week"},
    
    {thumbnail: 'imgs/tempo_thumbnail.jpg',
    channel: '../media/imgs/channel.PNG',
    title: "Made In The AM - Full",
    channelName: "Top Music Vevo",
    views: "13k",
    age: "1 week"},
    
    {thumbnail: 'imgs/tempo_thumbnail.jpg',
    channel: '../media/imgs/channel.PNG',
    title: "Made In The AM - Full",
    channelName: "Top Music Vevo",
    views: "13k",
    age: "1 week"},
    
    {thumbnail: 'imgs/tempo_thumbnail.jpg',
    channel: '../media/imgs/channel.PNG',
    title: "Made In The AM - Full",
    channelName: "Top Music Vevo",
    views: "13k",
    age: "1 week"},
    
    {thumbnail: 'imgs/tempo_thumbnail.jpg',
    channel: '../media/imgs/channel.PNG',
    title: "Made In The AM - Full",
    channelName: "Top Music Vevo",
    views: "13k",
    age: "1 week"},
    
    {thumbnail: 'imgs/tempo_thumbnail.jpg',
    channel: '../media/imgs/channel.PNG',
    title: "Made In The AM - Full",
    channelName: "Top Music Vevo",
    views: "13k",
    age: "1 week"},
    
    {thumbnail: 'imgs/tempo_thumbnail.jpg',
    channel: '../media/imgs/channel.PNG',
    title: "Made In The AM - Full",
    channelName: "Top Music Vevo",
    views: "13k",
    age: "1 week"}
]